### ISSUE TITLE
⭐Creating example bot. 

### ISSUE THREAD

**Issue by Lebyy** [Lebyy/VoiceTimeTrackerBot#1]
Since **discord-voice** **rewrite** is out an example for the bot will be required to showcase almost all of the functions and methods of the package.

**Comment by the-supernova** [comment]
Hi, I would like to work on this..just to be clear, do we have to write a bot using discord-voice package?

**Comment by Lebyy** [comment]
> Hi, I would like to work on this..just to be clear, do we have to write a bot using discord-voice package?

Yep!

**Comment by the-supernova** [comment]
Hi again, I am almost done with the bot, on the way of adding fetchUsers and fetchConfig commands. After finishing those, will send a PR by tomorrow.

**Comment by Lebyy** [comment]
Great! Alright :D
